# Generated by Django 5.1 on 2024-10-05 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactdata_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 8, 54, 52, 124807, tzinfo=datetime.timezone.utc)),
        ),
    ]
