# Generated by Django 5.1 on 2024-10-08 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contact_alter_news_publish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 10, 24, 29, 342036, tzinfo=datetime.timezone.utc)),
        ),
    ]
